### ISSUE TITLE
By default translates pages from English to English

### ISSUE THREAD

**Issue by MikkCZ** [BoringCode/TranslateThis#11]
Works quite well, but for me on current Firefox Nightly tries to translate all websites from English to English by default - I have to set the languages manually every time I want to translate any website.

**Comment by BoringCode** [comment]
Have you checked the options panel under about:addons? You can set the language there. 

If you have set the language, and still isn't working please let me know what OS you are using and any other information that you think might be helpful.

**Comment by MikkCZ** [comment]
Well, after setting the language in about:addons, it's in fact the same. I've set Czech and the add-on now opens a window with translation from Czech to Czech. The translation source language is detected only after the Google Translator page is reloaded (but still Czech is shown in the drop-down menu).

The link looks like http://translate.google.com/translate?js=n&prev=_t&ie=UTF-8&tl=cs&u=http%3A%2F%2Fphp.net%2F , maybe adding sl=auto inside might help to force the detection.

Just my suggestion, can be the target language set according to the browser locale, or according to the [language in Firefox preferences] (https://support.mozilla.org/kb/settings-fonts-languages-and-pop-ups)?

**Comment by BoringCode** [comment]
Okay, Czech is shown in the dropdown menu because you set it as your target language. The detection of the original language should happen automatically when you load the translate page (it worked for me on the link you sent).

I've thought about trying to detect the browser locale, but as I recall there were some issues with that. I will revisit it however.
